# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/company.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10v1/company.proto\"\xcb\x01\n\x07\x41\x64\x64ress\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0e\n\x06street\x18\x02 \x01(\t\x12\x0e\n\x06number\x18\x03 \x01(\t\x12\x12\n\ncomplement\x18\x04 \x01(\t\x12\x19\n\x0cneighborhood\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x0c\n\x04\x63ity\x18\x06 \x01(\t\x12\r\n\x05state\x18\x07 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x08 \x01(\t\x12\x0f\n\x07zipCode\x18\t \x01(\t\x12\x13\n\x0b\x63ompanyUuid\x18\n \x01(\tB\x0f\n\r_neighborhood\"j\n\x07\x43ompany\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05taxId\x18\x03 \x01(\t\x12\x11\n\ttradeName\x18\x04 \x01(\t\x12\x13\n\x0b\x66oundedDate\x18\x05 \x01(\t\x12\x0c\n\x04\x63nae\x18\x06 \x01(\t\"_\n\x0cRelationship\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x13\n\x0b\x63ompanyUuid\x18\x02 \x01(\t\x12\x12\n\npersonUuid\x18\x03 \x01(\t\x12\x18\n\x10relationshipType\x18\x04 \x01(\t\"-\n\x0e\x43ompanyRequest\x12\r\n\x05taxId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\",\n\x0f\x43ompanyResponse\x12\x19\n\x07\x63ompany\x18\x01 \x01(\x0b\x32\x08.Company\"2\n\x13RelationshipRequest\x12\r\n\x05taxId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"<\n\x14RelationshipResponse\x12$\n\rrelationships\x18\x01 \x03(\x0b\x32\r.Relationship2\xd8\x01\n\tCompanies\x12\x32\n\rCreateCompany\x12\x0f.CompanyRequest\x1a\x10.CompanyResponse\x12/\n\nGetCompany\x12\x0f.CompanyRequest\x1a\x10.CompanyResponse\x12\x32\n\rUpdateCompany\x12\x0f.CompanyRequest\x1a\x10.CompanyResponse\x12\x32\n\rDeleteCompany\x12\x0f.CompanyRequest\x1a\x10.CompanyResponse2D\n\rRelationships\x12\x33\n\x04Read\x12\x14.RelationshipRequest\x1a\x15.RelationshipResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.company_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ADDRESS']._serialized_start=21
  _globals['_ADDRESS']._serialized_end=224
  _globals['_COMPANY']._serialized_start=226
  _globals['_COMPANY']._serialized_end=332
  _globals['_RELATIONSHIP']._serialized_start=334
  _globals['_RELATIONSHIP']._serialized_end=429
  _globals['_COMPANYREQUEST']._serialized_start=431
  _globals['_COMPANYREQUEST']._serialized_end=476
  _globals['_COMPANYRESPONSE']._serialized_start=478
  _globals['_COMPANYRESPONSE']._serialized_end=522
  _globals['_RELATIONSHIPREQUEST']._serialized_start=524
  _globals['_RELATIONSHIPREQUEST']._serialized_end=574
  _globals['_RELATIONSHIPRESPONSE']._serialized_start=576
  _globals['_RELATIONSHIPRESPONSE']._serialized_end=636
  _globals['_COMPANIES']._serialized_start=639
  _globals['_COMPANIES']._serialized_end=855
  _globals['_RELATIONSHIPS']._serialized_start=857
  _globals['_RELATIONSHIPS']._serialized_end=925
# @@protoc_insertion_point(module_scope)
