# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kyc.grpcs.healthz.v1 import healthz_pb2 as kyc_dot_grpcs_dot_healthz_dot_v1_dot_healthz__pb2


class HealthzServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Healthz = channel.unary_unary(
                '/healthz.v1.HealthzService/Healthz',
                request_serializer=kyc_dot_grpcs_dot_healthz_dot_v1_dot_healthz__pb2.Empty.SerializeToString,
                response_deserializer=kyc_dot_grpcs_dot_healthz_dot_v1_dot_healthz__pb2.HealthzResponse.FromString,
                )


class HealthzServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Healthz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthzServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Healthz': grpc.unary_unary_rpc_method_handler(
                    servicer.Healthz,
                    request_deserializer=kyc_dot_grpcs_dot_healthz_dot_v1_dot_healthz__pb2.Empty.FromString,
                    response_serializer=kyc_dot_grpcs_dot_healthz_dot_v1_dot_healthz__pb2.HealthzResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'healthz.v1.HealthzService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HealthzService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Healthz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/healthz.v1.HealthzService/Healthz',
            kyc_dot_grpcs_dot_healthz_dot_v1_dot_healthz__pb2.Empty.SerializeToString,
            kyc_dot_grpcs_dot_healthz_dot_v1_dot_healthz__pb2.HealthzResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
