# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyc/grpcs/healthz/v1/healthz.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"kyc/grpcs/healthz/v1/healthz.proto\x12\nhealthz.v1\"\x07\n\x05\x45mpty\"!\n\x0fHealthzResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32M\n\x0eHealthzService\x12;\n\x07Healthz\x12\x11.healthz.v1.Empty\x1a\x1b.healthz.v1.HealthzResponse\"\x00\x42\x17Z\x15healthz/v1/go-healthzb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kyc.grpcs.healthz.v1.healthz_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\025healthz/v1/go-healthz'
  _globals['_EMPTY']._serialized_start=50
  _globals['_EMPTY']._serialized_end=57
  _globals['_HEALTHZRESPONSE']._serialized_start=59
  _globals['_HEALTHZRESPONSE']._serialized_end=92
  _globals['_HEALTHZSERVICE']._serialized_start=94
  _globals['_HEALTHZSERVICE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
