import pytest
import os
import subprocess
import textwrap

from tests.expected_files import base_files
from tests.utils import build_files_list, WIN, WORKING


@pytest.mark.parametrize('template', ['jinja2', 'mako', 'chameleon'])
def test_base(cookies, venv, capfd, template):
    result = cookies.bake(extra_context={
        'project_name': 'Test Project',
        'template_language': template,
        'persistence': 'none',
        'tasks': 'none',
        'repo_name': 'myapp',
    })

    assert result.exit_code == 0

    out, err = capfd.readouterr()

    if WIN:
        assert 'Scripts\\pserve' in out
        for idx, base_file in enumerate(base_files):
            base_files[idx] = base_file.replace('/', '\\')
        base_files.sort()

    else:
        assert 'bin/pserve' in out

    # Get the file list generated by cookiecutter. Differs based on backend.
    files = build_files_list(str(result.project_path))
    files.sort()

    # Rename files based on template being used
    if template == 'chameleon':
        template = 'pt'

    for idx, base_file in enumerate(base_files):
        if 'templates' in base_file:
            base_files[idx] = base_files[idx].split('.')[0] + '.' + template

    assert base_files == files
