version: '3'
services:
  dev-service:
      # Note that the path of the Dockerfile and context is relative to the *primary*
      # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
      # array). The sample below assumes your primary file is in the root of your project.
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "ubuntu-22.04"
    links:
      - redis:rs
      - postgres:postgresdb
    volumes:
      - /Users/tomas/Documents/workspace/business-pipeline:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - internal

  conductor:
    build:
      context: ../.
      dockerfile: conductor/Dockerfile
    depends_on:
      - postgres
      - redis
    links:
      - redis:rediss
      - postgres:postgresdb
    ports:
      - "1234:5000"
      - "8080:8080"
    networks:
      - internal
    environment:
      # - DO_NOT_START_APP=true
      # - CONFIG_PROP=config-postgres.properties
      - CONDUCTOR_REDIS_HOST=redis:6379:1
      - CONDUCTOR_REDIS_LOCK_SERVER_ADDRESS=redis://redis:6379

  postgres:
    # container_name: postgres_container
    image: postgres:15.3
    environment:
      POSTGRES_USER: conductor
      POSTGRES_PASSWORD: conductor
      POSTGRES_DB: conductor
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    # ports:
    #   - "5432:5432"
    networks:
      - internal
    restart: unless-stopped
  
  redis:
    image: redis:6.2-alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    # ports:
    #   - '6379:6379'
    networks:
      - internal
    command: redis-server --loglevel warning
    volumes: 
      - redis:/data

networks:
  internal:

volumes:
    postgres:
    redis:
