name: Unit Tests CI

on:
  pull_request:
    branches:
      - staging
      - production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Python Tests
        uses: cartaorobbin/python-tests-action@v0.1.0-beta
        with:
          version: '3.11' 